linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - gocritic
    - predeclared

linters-settings:
  errcheck:
    check-type-assertions: true
  # Use gocritic for shadow variable detection instead of the deprecated govet option
  gocritic:
    enabled-checks:
      - builtinShadow
      - importShadow
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "disableStutteringCheck"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  modules-download-mode: readonly